# Generated by Django 5.1.2 on 2025-01-21 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='baggage_preference',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='meal_preference',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='seat_preference',
        ),
        migrations.AddField(
            model_name='passenger',
            name='baggage_preference',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='accounts.baggage'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='meal_preference',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='accounts.meal'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='seat_preference',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='accounts.seat'),
        ),
    ]
