# Generated by Django 5.1.2 on 2025-02-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='carriers',
            new_name='elevation',
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='code',
            new_name='iata',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='direct_flights',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='elev',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='email',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='runway_length',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='type',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='url',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='woeid',
        ),
        migrations.AlterField(
            model_name='airport',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
