# Generated by Django 5.1.2 on 2025-02-26 03:27
# Updated: add search_vector in a DB-agnostic way (PostgreSQL SearchVectorField, SQLite TextField)

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models, connection


def add_search_vector_and_indexes(apps, schema_editor):
    Airport = apps.get_model('flights', 'Airport')
    vendor = connection.vendor
    if vendor == 'postgresql':
        schema_editor.add_field(Airport, django.contrib.postgres.search.SearchVectorField(null=True))
        schema_editor.add_index(Airport, django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='flights_air_search__adf1f4_gin'))
    else:
        schema_editor.execute('ALTER TABLE flights_airport ADD COLUMN search_vector TEXT NULL')
    schema_editor.add_index(Airport, models.Index(fields=['iata'], name='flights_air_iata_ad2905_idx'))
    schema_editor.add_index(Airport, models.Index(fields=['name'], name='flights_air_name_218b6b_idx'))


def remove_search_vector_and_indexes(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_rename_carriers_airport_elevation_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='airport',
                    name='search_vector',
                    field=django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                migrations.AddIndex(
                    model_name='airport',
                    index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='flights_air_search__adf1f4_gin'),
                ),
                migrations.AddIndex(
                    model_name='airport',
                    index=models.Index(fields=['iata'], name='flights_air_iata_ad2905_idx'),
                ),
                migrations.AddIndex(
                    model_name='airport',
                    index=models.Index(fields=['name'], name='flights_air_name_218b6b_idx'),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_search_vector_and_indexes, remove_search_vector_and_indexes),
            ],
        ),
    ]
