# Generated by Django 5.1.2 on 2025-06-18 14:12
# Alters search_vector on PostgreSQL only; state updated for all DBs

import django.contrib.postgres.search
from django.db import migrations, connection


def alter_search_vector_if_postgres(apps, schema_editor):
    if connection.vendor != 'postgresql':
        return
    Airport = apps.get_model('flights', 'Airport')
    old_field = django.contrib.postgres.search.SearchVectorField(null=True)
    new_field = django.contrib.postgres.search.SearchVectorField(blank=True, null=True)
    schema_editor.alter_field(Airport, old_field, new_field)


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_airport_search_vector_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='airport',
                    name='search_vector',
                    field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
                ),
            ],
            database_operations=[
                migrations.RunPython(alter_search_vector_if_postgres, migrations.RunPython.noop),
            ],
        ),
    ]
