# Generated by Django 5.1.2 on 2026-02-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_airport_search_vector'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='airport',
            name='flights_air_search__adf1f4_gin',
        ),
        migrations.AlterField(
            model_name='airport',
            name='search_vector',
            field=models.TextField(blank=True, null=True),
        ),
    ]
