# Generated by Django 5.1.2 on 2024-11-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Mstr', 'Mstr')], max_length=5)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('pax_type', models.IntegerField(choices=[(1, 'Adult'), (2, 'Child'), (3, 'Infant')])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('passport_no', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=2)),
                ('country_name', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('is_lead_pax', models.BooleanField()),
                ('ff_airline_code', models.CharField(blank=True, max_length=10, null=True)),
                ('ff_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gst_company_address', models.CharField(max_length=100)),
                ('gst_company_contact_number', models.CharField(max_length=20)),
                ('gst_company_name', models.CharField(max_length=100)),
                ('gst_number', models.CharField(max_length=20)),
                ('gst_company_email', models.EmailField(max_length=254)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yq_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_txn_fee_ofrd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_txn_fee_pub', models.DecimalField(decimal_places=2, max_digits=10)),
                ('air_trans_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
