# Generated by Django 5.1.2 on 2024-11-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hexid', models.CharField(default='88509c070609433abef2a6e0e348960c', max_length=24, unique=True)),
                ('traceId', models.CharField(blank=True, max_length=100, null=True)),
                ('resultIndex', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
