# Generated by Django 5.1.2 on 2024-11-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_searchsession_passengers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchsession',
            name='baggage',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchsession',
            name='meals',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchsession',
            name='seats',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchsession',
            name='hexid',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
