# Generated by Django 5.1.2 on 2024-11-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_searchsession_baggage_searchsession_meals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchsession',
            name='expiry',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
