# Generated by Django 5.1.2 on 2024-11-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_searchsession_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchsession',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='searchsession',
            name='primaryContact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='searchsession',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
