# Generated by Django 5.1.2 on 2024-11-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_searchsession_email_searchsession_primarycontact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='bookingId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='pnr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
