# Generated by Django 5.1.2 on 2024-11-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_passenger_bookingid_passenger_pnr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='bookingId',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='pnr',
        ),
        migrations.AddField(
            model_name='searchsession',
            name='bookingId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='searchsession',
            name='paxId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='searchsession',
            name='pnr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
