# Generated by Django 5.1.2 on 2024-11-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_passenger_bookingid_remove_passenger_pnr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='passport_issue',
            field=models.DateField(blank=True, null=True),
        ),
    ]
