# Generated by Django 5.1.2 on 2024-11-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_passenger_passport_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchsession',
            name='paxId',
        ),
        migrations.AddField(
            model_name='searchsession',
            name='booking_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
