# Generated by Django 5.1.2 on 2024-11-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_searchsession_paxid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchsession',
            name='isLcc',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
