# Generated by Django 5.1.2 on 2024-11-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_searchsession_islcc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='additional_txn_fee_ofrd',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='additional_txn_fee_pub',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='air_trans_fee',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='base_fare',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='ff_airline_code',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='ff_number',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='gst_company_address',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='gst_company_contact_number',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='gst_company_email',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='gst_company_name',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='transaction_fee',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='yq_tax',
        ),
        migrations.AddField(
            model_name='searchsession',
            name='additional_txn_fee_ofrd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='searchsession',
            name='additional_txn_fee_pub',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='searchsession',
            name='air_trans_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='searchsession',
            name='base_fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='searchsession',
            name='gst_company_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='searchsession',
            name='gst_company_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='searchsession',
            name='gst_company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='searchsession',
            name='gst_company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='searchsession',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='searchsession',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='searchsession',
            name='transaction_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='searchsession',
            name='yq_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
