# Generated by Django 5.1.2 on 2024-11-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_passenger_additional_txn_fee_ofrd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='baggage_preference',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='meal_preference',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='seat_preference',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
