# Generated by Django 5.1.2 on 2024-11-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_passenger_baggage_preference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baggage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AirlineCode', models.CharField(blank=True, max_length=10, null=True)),
                ('FlightNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('WayType', models.IntegerField(blank=True, null=True)),
                ('Code', models.CharField(blank=True, max_length=10, null=True)),
                ('Description', models.IntegerField(blank=True, null=True)),
                ('Weight', models.IntegerField(blank=True, null=True)),
                ('Currency', models.CharField(blank=True, max_length=10, null=True)),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Origin', models.CharField(blank=True, max_length=10, null=True)),
                ('Destination', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AirlineCode', models.CharField(blank=True, max_length=10, null=True)),
                ('FlightNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('WayType', models.IntegerField(blank=True, null=True)),
                ('Code', models.CharField(blank=True, max_length=10, null=True)),
                ('Description', models.IntegerField(blank=True, null=True)),
                ('AirlineDescription', models.CharField(blank=True, max_length=100, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Currency', models.CharField(blank=True, max_length=10, null=True)),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Origin', models.CharField(blank=True, max_length=10, null=True)),
                ('Destination', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AirlineCode', models.CharField(blank=True, max_length=10, null=True)),
                ('FlightNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('CraftType', models.CharField(blank=True, max_length=10, null=True)),
                ('Origin', models.CharField(blank=True, max_length=10, null=True)),
                ('Destination', models.CharField(blank=True, max_length=10, null=True)),
                ('AvailablityType', models.IntegerField(blank=True, null=True)),
                ('Description', models.IntegerField(blank=True, null=True)),
                ('Code', models.CharField(blank=True, max_length=10, null=True)),
                ('RowNo', models.CharField(blank=True, max_length=10, null=True)),
                ('SeatNo', models.CharField(blank=True, max_length=10, null=True)),
                ('SeatType', models.IntegerField(blank=True, null=True)),
                ('SeatWayType', models.IntegerField(blank=True, null=True)),
                ('Compartment', models.IntegerField(blank=True, null=True)),
                ('Deck', models.IntegerField(blank=True, null=True)),
                ('Currency', models.CharField(blank=True, max_length=10, null=True)),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='baggage_preference',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='meal_preference',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='seat_preference',
        ),
        migrations.AddField(
            model_name='passenger',
            name='baggage_preference',
            field=models.ManyToManyField(blank=True, related_name='passengers', to='home.baggage'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='meal_preference',
            field=models.ManyToManyField(blank=True, related_name='passengers', to='home.meal'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='seat_preference',
            field=models.ManyToManyField(blank=True, related_name='passengers', to='home.seat'),
        ),
    ]
