# Generated by Django 5.1.2 on 2025-01-01 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_baggage_meal_seat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Currency', models.CharField(blank=True, max_length=10, null=True)),
                ('BaseFare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('YQTax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('AdditionalTxnFeeOfrd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('AdditionalTxnFeePub', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('OtherCharges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('PublishedFare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('OfferedFare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('TdsOnCommission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('TdsOnPLB', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('TdsOnIncentive', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ServiceFee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('air_trans_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='searchsession',
            name='additional_txn_fee_ofrd',
        ),
        migrations.RemoveField(
            model_name='searchsession',
            name='additional_txn_fee_pub',
        ),
        migrations.RemoveField(
            model_name='searchsession',
            name='air_trans_fee',
        ),
        migrations.RemoveField(
            model_name='searchsession',
            name='base_fare',
        ),
        migrations.RemoveField(
            model_name='searchsession',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='searchsession',
            name='transaction_fee',
        ),
        migrations.RemoveField(
            model_name='searchsession',
            name='yq_tax',
        ),
        migrations.AddField(
            model_name='passenger',
            name='fare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.fare'),
        ),
    ]
