# Generated by Django 5.1.2 on 2025-01-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_fare_remove_searchsession_additional_txn_fee_ofrd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchsession',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('failed', 'Failed'), ('success', 'Success')], default='pending', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='searchsession',
            name='ticket_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
