# Generated by Django 5.1.2 on 2025-01-03 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_searchsession_isticketed_paymenttransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traceId', models.CharField(blank=True, max_length=100, null=True)),
                ('bookingId', models.CharField(blank=True, max_length=50, null=True)),
                ('pnr', models.CharField(blank=True, max_length=50, null=True)),
                ('JourneyType', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='searchsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
