# Generated by Django 5.1.2 on 2025-01-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_booking_searchsession_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_image', models.URLField(blank=True, null=True)),
                ('hub', models.CharField(max_length=255)),
                ('call_sign', models.CharField(blank=True, max_length=100, null=True)),
                ('headquarters', models.CharField(max_length=255)),
                ('popular_route', models.CharField(blank=True, max_length=255, null=True)),
                ('popular_destinations', models.JSONField(blank=True, null=True)),
                ('travel_insights', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('history_highlight', models.TextField(blank=True, null=True)),
                ('faqs', models.JSONField(blank=True, null=True)),
                ('support_number', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='baggage_preference',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='fare',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='meal_preference',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='seat_preference',
        ),
        migrations.RemoveField(
            model_name='searchsession',
            name='passengers',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='search_session',
        ),
        migrations.RemoveField(
            model_name='searchsession',
            name='user',
        ),
        migrations.DeleteModel(
            name='Baggage',
        ),
        migrations.DeleteModel(
            name='Fare',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
        migrations.DeleteModel(
            name='SearchSession',
        ),
    ]
