# Generated by Django 5.1.2 on 2025-02-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_airline_remove_passenger_baggage_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
