# Generated by Django 5.1.2 on 2025-02-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_airline_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airline',
            old_name='history_highlight',
            new_name='booking_tips',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='faqs',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='travel_insights',
        ),
        migrations.AddField(
            model_name='airline',
            name='child_travelers_percentage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='faq_carry_on',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='faq_cheap_flights',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='faq_checked_baggage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='faq_cities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='faq_rewards_program',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='female_travelers_percentage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='millennial_travelers_percentage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='most_popular_airport',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='most_popular_destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='premium_class_bookings_percentage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='senior_travelers_percentage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='airline',
            name='popular_destinations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
