# Generated by Django 5.1.2 on 2025-02-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_history_highlight_airline_booking_tips_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='airline',
            name='faq_carry_on',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='faq_cheap_flights',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='faq_checked_baggage',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='faq_cities',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='faq_rewards_program',
        ),
        migrations.AddField(
            model_name='airline',
            name='faq',
            field=models.ManyToManyField(blank=True, to='home.faq'),
        ),
    ]
