# Generated by Django 5.1.2 on 2025-02-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_faq_remove_airline_faq_carry_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitedTimeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='limited_time_offers/')),
                ('discount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('destination', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='PopularDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='popular_destinations/')),
                ('rating', models.IntegerField()),
                ('price', models.IntegerField()),
                ('destination', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TrendingDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='trending_destinations/')),
                ('rating', models.IntegerField()),
                ('price', models.IntegerField()),
                ('destination', models.CharField(max_length=5)),
            ],
        ),
    ]
