# Generated by Django 5.1.2 on 2025-02-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_limitedtimeoffer_populardestination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitedtimeoffer',
            name='discount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='limitedtimeoffer',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='populardestination',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='populardestination',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trendingdestination',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trendingdestination',
            name='rating',
            field=models.FloatField(),
        ),
    ]
