# Generated by Django 5.1.2 on 2025-02-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
        migrations.AddField(
            model_name='blog',
            name='hex',
            field=models.CharField(blank=True, editable=False, max_length=32, unique=True),
        ),
    ]
