# Generated by Django 5.1.2 on 2025-02-26 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_blog_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='view_count',
        ),
    ]
