# Generated by Django 5.1.2 on 2025-02-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_remove_blog_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.CharField(blank=True, help_text='Space-separated tags', max_length=255),
        ),
    ]
