# Generated by Django 5.1.2 on 2025-03-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='airlines/'),
        ),
    ]
