# Generated by Django 5.1.2 on 2025-03-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_airline_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirlineVacationPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='airline_vacation_packages/')),
                ('rating', models.FloatField()),
                ('price', models.FloatField()),
                ('destination', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='InternationalFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='international_flights/')),
                ('rating', models.FloatField()),
                ('price', models.FloatField()),
                ('destination', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='LastMinuteFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='last_minute_flights/')),
                ('rating', models.FloatField()),
                ('price', models.FloatField()),
                ('destination', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='NonStopFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='non_stop_flights/')),
                ('rating', models.FloatField()),
                ('price', models.FloatField()),
                ('destination', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='OneWayFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='one_way_flights/')),
                ('rating', models.FloatField()),
                ('price', models.FloatField()),
                ('destination', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='RoundTripFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='round_trip_flights/')),
                ('rating', models.FloatField()),
                ('price', models.FloatField()),
                ('destination', models.CharField(max_length=5)),
            ],
        ),
        migrations.RenameModel(
            old_name='PopularDestination',
            new_name='CityVacationPackage',
        ),
        migrations.RenameModel(
            old_name='LimitedTimeOffer',
            new_name='DirectFlight',
        ),
        migrations.RenameModel(
            old_name='TrendingDestination',
            new_name='FlightFrom',
        ),
    ]
