# Generated by Django 5.1.2 on 2025-03-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_airlinevacationpackage_internationalflight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airlinevacationpackage',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='cityvacationpackage',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='directflight',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='flightfrom',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='internationalflight',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='lastminuteflight',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='nonstopflight',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='onewayflight',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='roundtripflight',
            name='destination',
        ),
        migrations.AlterField(
            model_name='airlinevacationpackage',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airlinevacationpackage',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cityvacationpackage',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cityvacationpackage',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='directflight',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='directflight',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightfrom',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightfrom',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internationalflight',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internationalflight',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lastminuteflight',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lastminuteflight',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nonstopflight',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nonstopflight',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onewayflight',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onewayflight',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roundtripflight',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roundtripflight',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
