# Generated by Django 5.1.2 on 2025-03-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_remove_airlinevacationpackage_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directflight',
            name='description',
        ),
        migrations.AddField(
            model_name='directflight',
            name='advantages',
            field=models.TextField(help_text='Bullet list or description of the advantages (e.g., time-saving, less hassle, more comfortable).', null=True),
        ),
        migrations.AddField(
            model_name='directflight',
            name='advantages_heading',
            field=models.CharField(default='Why Choose a Direct Flight to Costa Rica?', help_text='Heading for the advantages section.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='directflight',
            name='airlines_heading',
            field=models.CharField(default='Major Airlines Offering Direct Flights to Costa Rica', help_text='Heading for the airlines section.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='directflight',
            name='airports_heading',
            field=models.CharField(default='International Airports Serving Costa Rica', help_text='Heading for the airports information section.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='directflight',
            name='airports_info',
            field=models.TextField(help_text='Details about key international airports in Costa Rica (e.g., Juan Santamaría International Airport (SJO) and Daniel Oduber Quirós International Airport (LIR)).', null=True),
        ),
        migrations.AddField(
            model_name='directflight',
            name='booking_tips',
            field=models.TextField(help_text='Tips for booking flights, such as booking early, traveling in the off-season, and using fare alerts.', null=True),
        ),
        migrations.AddField(
            model_name='directflight',
            name='booking_tips_heading',
            field=models.CharField(default='Best Time to Book Direct Flights to Costa Rica', help_text='Heading for the booking tips section.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='directflight',
            name='cities_heading',
            field=models.CharField(default='Popular Cities with Direct Flights to Costa Rica', help_text='Heading for the cities section.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='directflight',
            name='conclusion',
            field=models.TextField(help_text='Concluding call-to-action content, encouraging users to book their direct flight.', null=True),
        ),
        migrations.AddField(
            model_name='directflight',
            name='finding_tips',
            field=models.TextField(help_text='Step-by-step instructions on how to find affordable flight options, including flexible dates and nearby airports.', null=True),
        ),
        migrations.AddField(
            model_name='directflight',
            name='finding_tips_heading',
            field=models.CharField(default='How to Find Cheap Direct Flights to Costa Rica', help_text='Heading for the flight finding tips section.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='directflight',
            name='intro',
            field=models.TextField(help_text='Introduction text with an overview of direct flights to Costa Rica.', null=True),
        ),
        migrations.AddField(
            model_name='directflight',
            name='major_airlines',
            field=models.TextField(help_text='List of major airlines (e.g., American Airlines, Delta Airlines, etc.).', null=True),
        ),
        migrations.AddField(
            model_name='directflight',
            name='popular_cities',
            field=models.TextField(help_text='Details and bullet points of popular departure cities from various regions.', null=True),
        ),
        migrations.AddField(
            model_name='directflight',
            name='travel_info',
            field=models.TextField(help_text='Important travel details including entry requirements, currency and payment options, and time zone information.', null=True),
        ),
        migrations.AddField(
            model_name='directflight',
            name='travel_info_heading',
            field=models.CharField(default='Things to Know Before Flying to Costa Rica', help_text='Heading for the travel information section.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='directflight',
            name='discount',
            field=models.FloatField(blank=True, help_text='Discount percentage if applicable.', null=True),
        ),
        migrations.AlterField(
            model_name='directflight',
            name='image',
            field=models.ImageField(help_text='Promotional image for the direct flight offer.', null=True, upload_to='limited_time_offers/'),
        ),
        migrations.AlterField(
            model_name='directflight',
            name='price',
            field=models.FloatField(blank=True, help_text='Price for the direct flight offer.', null=True),
        ),
        migrations.AlterField(
            model_name='directflight',
            name='title',
            field=models.CharField(help_text="Title of the content, e.g., 'Direct Flights to Costa'", max_length=255, null=True),
        ),
    ]
