# Generated by Django 5.1.2 on 2025-03-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_remove_directflight_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directflight',
            name='slug',
            field=models.SlugField(editable=False, null=True),
        ),
    ]
