# Generated by Django 5.1.2 on 2025-03-20 07:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_directflight_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directflight',
            name='airports_heading',
        ),
        migrations.RemoveField(
            model_name='directflight',
            name='airports_info',
        ),
        migrations.RemoveField(
            model_name='directflight',
            name='booking_tips',
        ),
        migrations.RemoveField(
            model_name='directflight',
            name='booking_tips_heading',
        ),
        migrations.RemoveField(
            model_name='directflight',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='directflight',
            name='finding_tips',
        ),
        migrations.RemoveField(
            model_name='directflight',
            name='finding_tips_heading',
        ),
        migrations.RemoveField(
            model_name='directflight',
            name='travel_info',
        ),
        migrations.RemoveField(
            model_name='directflight',
            name='travel_info_heading',
        ),
        migrations.AddField(
            model_name='directflight',
            name='faq',
            field=models.ManyToManyField(blank=True, to='home.faq'),
        ),
        migrations.AlterField(
            model_name='directflight',
            name='advantages',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='directflight',
            name='advantages_heading',
            field=models.CharField(default='', help_text='Heading for the advantages section.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='directflight',
            name='airlines_heading',
            field=models.CharField(help_text='Heading for the airlines section.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='directflight',
            name='cities_heading',
            field=models.CharField(help_text='Heading for the cities section.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='directflight',
            name='intro',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='directflight',
            name='major_airlines',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='directflight',
            name='popular_cities',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
