# Generated by Django 5.1.2 on 2025-03-20 08:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_remove_directflight_airports_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airlinevacationpackage',
            name='advantages',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='airlinevacationpackage',
            name='advantages_heading',
            field=models.CharField(default='', help_text='Heading for the advantages section.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='airlinevacationpackage',
            name='airlines_heading',
            field=models.CharField(help_text='Heading for the airlines section.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='airlinevacationpackage',
            name='cities_heading',
            field=models.CharField(help_text='Heading for the cities section.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='airlinevacationpackage',
            name='discount',
            field=models.FloatField(blank=True, help_text='Discount percentage if applicable.', null=True),
        ),
        migrations.AddField(
            model_name='airlinevacationpackage',
            name='faq',
            field=models.ManyToManyField(blank=True, to='home.faq'),
        ),
        migrations.AddField(
            model_name='airlinevacationpackage',
            name='intro',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='airlinevacationpackage',
            name='major_airlines',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='airlinevacationpackage',
            name='popular_cities',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='airlinevacationpackage',
            name='slug',
            field=models.SlugField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='cityvacationpackage',
            name='advantages',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='cityvacationpackage',
            name='advantages_heading',
            field=models.CharField(default='', help_text='Heading for the advantages section.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cityvacationpackage',
            name='airlines_heading',
            field=models.CharField(help_text='Heading for the airlines section.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cityvacationpackage',
            name='cities_heading',
            field=models.CharField(help_text='Heading for the cities section.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cityvacationpackage',
            name='discount',
            field=models.FloatField(blank=True, help_text='Discount percentage if applicable.', null=True),
        ),
        migrations.AddField(
            model_name='cityvacationpackage',
            name='faq',
            field=models.ManyToManyField(blank=True, to='home.faq'),
        ),
        migrations.AddField(
            model_name='cityvacationpackage',
            name='intro',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='cityvacationpackage',
            name='major_airlines',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='cityvacationpackage',
            name='popular_cities',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='cityvacationpackage',
            name='slug',
            field=models.SlugField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='directflight',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='directflight',
            name='rating',
            field=models.FloatField(blank=True, help_text='Rating for the direct flight offer.', null=True),
        ),
        migrations.AddField(
            model_name='flightfrom',
            name='advantages',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='flightfrom',
            name='advantages_heading',
            field=models.CharField(default='', help_text='Heading for the advantages section.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='flightfrom',
            name='airlines_heading',
            field=models.CharField(help_text='Heading for the airlines section.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='flightfrom',
            name='cities_heading',
            field=models.CharField(help_text='Heading for the cities section.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='flightfrom',
            name='discount',
            field=models.FloatField(blank=True, help_text='Discount percentage if applicable.', null=True),
        ),
        migrations.AddField(
            model_name='flightfrom',
            name='faq',
            field=models.ManyToManyField(blank=True, to='home.faq'),
        ),
        migrations.AddField(
            model_name='flightfrom',
            name='intro',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='flightfrom',
            name='major_airlines',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='flightfrom',
            name='popular_cities',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='flightfrom',
            name='slug',
            field=models.SlugField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='internationalflight',
            name='advantages',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='internationalflight',
            name='advantages_heading',
            field=models.CharField(default='', help_text='Heading for the advantages section.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalflight',
            name='airlines_heading',
            field=models.CharField(help_text='Heading for the airlines section.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalflight',
            name='cities_heading',
            field=models.CharField(help_text='Heading for the cities section.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalflight',
            name='discount',
            field=models.FloatField(blank=True, help_text='Discount percentage if applicable.', null=True),
        ),
        migrations.AddField(
            model_name='internationalflight',
            name='faq',
            field=models.ManyToManyField(blank=True, to='home.faq'),
        ),
        migrations.AddField(
            model_name='internationalflight',
            name='intro',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='internationalflight',
            name='major_airlines',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='internationalflight',
            name='popular_cities',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='internationalflight',
            name='slug',
            field=models.SlugField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='lastminuteflight',
            name='advantages',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='lastminuteflight',
            name='advantages_heading',
            field=models.CharField(default='', help_text='Heading for the advantages section.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lastminuteflight',
            name='airlines_heading',
            field=models.CharField(help_text='Heading for the airlines section.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lastminuteflight',
            name='cities_heading',
            field=models.CharField(help_text='Heading for the cities section.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lastminuteflight',
            name='discount',
            field=models.FloatField(blank=True, help_text='Discount percentage if applicable.', null=True),
        ),
        migrations.AddField(
            model_name='lastminuteflight',
            name='faq',
            field=models.ManyToManyField(blank=True, to='home.faq'),
        ),
        migrations.AddField(
            model_name='lastminuteflight',
            name='intro',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='lastminuteflight',
            name='major_airlines',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='lastminuteflight',
            name='popular_cities',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='lastminuteflight',
            name='slug',
            field=models.SlugField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='nonstopflight',
            name='advantages',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='nonstopflight',
            name='advantages_heading',
            field=models.CharField(default='', help_text='Heading for the advantages section.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nonstopflight',
            name='airlines_heading',
            field=models.CharField(help_text='Heading for the airlines section.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nonstopflight',
            name='cities_heading',
            field=models.CharField(help_text='Heading for the cities section.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nonstopflight',
            name='discount',
            field=models.FloatField(blank=True, help_text='Discount percentage if applicable.', null=True),
        ),
        migrations.AddField(
            model_name='nonstopflight',
            name='faq',
            field=models.ManyToManyField(blank=True, to='home.faq'),
        ),
        migrations.AddField(
            model_name='nonstopflight',
            name='intro',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='nonstopflight',
            name='major_airlines',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='nonstopflight',
            name='popular_cities',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='nonstopflight',
            name='slug',
            field=models.SlugField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='onewayflight',
            name='advantages',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='onewayflight',
            name='advantages_heading',
            field=models.CharField(default='', help_text='Heading for the advantages section.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='onewayflight',
            name='airlines_heading',
            field=models.CharField(help_text='Heading for the airlines section.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='onewayflight',
            name='cities_heading',
            field=models.CharField(help_text='Heading for the cities section.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='onewayflight',
            name='discount',
            field=models.FloatField(blank=True, help_text='Discount percentage if applicable.', null=True),
        ),
        migrations.AddField(
            model_name='onewayflight',
            name='faq',
            field=models.ManyToManyField(blank=True, to='home.faq'),
        ),
        migrations.AddField(
            model_name='onewayflight',
            name='intro',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='onewayflight',
            name='major_airlines',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='onewayflight',
            name='popular_cities',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='onewayflight',
            name='slug',
            field=models.SlugField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='roundtripflight',
            name='advantages',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='roundtripflight',
            name='advantages_heading',
            field=models.CharField(default='', help_text='Heading for the advantages section.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='roundtripflight',
            name='airlines_heading',
            field=models.CharField(help_text='Heading for the airlines section.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='roundtripflight',
            name='cities_heading',
            field=models.CharField(help_text='Heading for the cities section.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='roundtripflight',
            name='discount',
            field=models.FloatField(blank=True, help_text='Discount percentage if applicable.', null=True),
        ),
        migrations.AddField(
            model_name='roundtripflight',
            name='faq',
            field=models.ManyToManyField(blank=True, to='home.faq'),
        ),
        migrations.AddField(
            model_name='roundtripflight',
            name='intro',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='roundtripflight',
            name='major_airlines',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='roundtripflight',
            name='popular_cities',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='roundtripflight',
            name='slug',
            field=models.SlugField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='airlinevacationpackage',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='airlinevacationpackage',
            name='image',
            field=models.ImageField(help_text='Promotional image for the direct flight offer.', null=True, upload_to='limited_time_offers/'),
        ),
        migrations.AlterField(
            model_name='airlinevacationpackage',
            name='price',
            field=models.FloatField(blank=True, help_text='Price for the direct flight offer.', null=True),
        ),
        migrations.AlterField(
            model_name='airlinevacationpackage',
            name='rating',
            field=models.FloatField(blank=True, help_text='Rating for the direct flight offer.', null=True),
        ),
        migrations.AlterField(
            model_name='airlinevacationpackage',
            name='title',
            field=models.CharField(help_text="Title of the content, e.g., 'Direct Flights to Costa'", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cityvacationpackage',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cityvacationpackage',
            name='image',
            field=models.ImageField(help_text='Promotional image for the direct flight offer.', null=True, upload_to='limited_time_offers/'),
        ),
        migrations.AlterField(
            model_name='cityvacationpackage',
            name='price',
            field=models.FloatField(blank=True, help_text='Price for the direct flight offer.', null=True),
        ),
        migrations.AlterField(
            model_name='cityvacationpackage',
            name='rating',
            field=models.FloatField(blank=True, help_text='Rating for the direct flight offer.', null=True),
        ),
        migrations.AlterField(
            model_name='cityvacationpackage',
            name='title',
            field=models.CharField(help_text="Title of the content, e.g., 'Direct Flights to Costa'", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flightfrom',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='flightfrom',
            name='image',
            field=models.ImageField(help_text='Promotional image for the direct flight offer.', null=True, upload_to='limited_time_offers/'),
        ),
        migrations.AlterField(
            model_name='flightfrom',
            name='price',
            field=models.FloatField(blank=True, help_text='Price for the direct flight offer.', null=True),
        ),
        migrations.AlterField(
            model_name='flightfrom',
            name='rating',
            field=models.FloatField(blank=True, help_text='Rating for the direct flight offer.', null=True),
        ),
        migrations.AlterField(
            model_name='flightfrom',
            name='title',
            field=models.CharField(help_text="Title of the content, e.g., 'Direct Flights to Costa'", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internationalflight',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='internationalflight',
            name='image',
            field=models.ImageField(help_text='Promotional image for the direct flight offer.', null=True, upload_to='limited_time_offers/'),
        ),
        migrations.AlterField(
            model_name='internationalflight',
            name='price',
            field=models.FloatField(blank=True, help_text='Price for the direct flight offer.', null=True),
        ),
        migrations.AlterField(
            model_name='internationalflight',
            name='rating',
            field=models.FloatField(blank=True, help_text='Rating for the direct flight offer.', null=True),
        ),
        migrations.AlterField(
            model_name='internationalflight',
            name='title',
            field=models.CharField(help_text="Title of the content, e.g., 'Direct Flights to Costa'", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lastminuteflight',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lastminuteflight',
            name='image',
            field=models.ImageField(help_text='Promotional image for the direct flight offer.', null=True, upload_to='limited_time_offers/'),
        ),
        migrations.AlterField(
            model_name='lastminuteflight',
            name='price',
            field=models.FloatField(blank=True, help_text='Price for the direct flight offer.', null=True),
        ),
        migrations.AlterField(
            model_name='lastminuteflight',
            name='rating',
            field=models.FloatField(blank=True, help_text='Rating for the direct flight offer.', null=True),
        ),
        migrations.AlterField(
            model_name='lastminuteflight',
            name='title',
            field=models.CharField(help_text="Title of the content, e.g., 'Direct Flights to Costa'", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nonstopflight',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='nonstopflight',
            name='image',
            field=models.ImageField(help_text='Promotional image for the direct flight offer.', null=True, upload_to='limited_time_offers/'),
        ),
        migrations.AlterField(
            model_name='nonstopflight',
            name='price',
            field=models.FloatField(blank=True, help_text='Price for the direct flight offer.', null=True),
        ),
        migrations.AlterField(
            model_name='nonstopflight',
            name='rating',
            field=models.FloatField(blank=True, help_text='Rating for the direct flight offer.', null=True),
        ),
        migrations.AlterField(
            model_name='nonstopflight',
            name='title',
            field=models.CharField(help_text="Title of the content, e.g., 'Direct Flights to Costa'", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='onewayflight',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='onewayflight',
            name='image',
            field=models.ImageField(help_text='Promotional image for the direct flight offer.', null=True, upload_to='limited_time_offers/'),
        ),
        migrations.AlterField(
            model_name='onewayflight',
            name='price',
            field=models.FloatField(blank=True, help_text='Price for the direct flight offer.', null=True),
        ),
        migrations.AlterField(
            model_name='onewayflight',
            name='rating',
            field=models.FloatField(blank=True, help_text='Rating for the direct flight offer.', null=True),
        ),
        migrations.AlterField(
            model_name='onewayflight',
            name='title',
            field=models.CharField(help_text="Title of the content, e.g., 'Direct Flights to Costa'", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='roundtripflight',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='roundtripflight',
            name='image',
            field=models.ImageField(help_text='Promotional image for the direct flight offer.', null=True, upload_to='limited_time_offers/'),
        ),
        migrations.AlterField(
            model_name='roundtripflight',
            name='price',
            field=models.FloatField(blank=True, help_text='Price for the direct flight offer.', null=True),
        ),
        migrations.AlterField(
            model_name='roundtripflight',
            name='rating',
            field=models.FloatField(blank=True, help_text='Rating for the direct flight offer.', null=True),
        ),
        migrations.AlterField(
            model_name='roundtripflight',
            name='title',
            field=models.CharField(help_text="Title of the content, e.g., 'Direct Flights to Costa'", max_length=255, null=True),
        ),
    ]
