# Generated by Django 5.1.2 on 2025-04-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_airlinevacationpackage_advantages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
