# Generated by Django 5.1.2 on 2025-04-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_homefaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='metaDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='metaTitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='airlinevacationpackage',
            name='metaDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airlinevacationpackage',
            name='metaTitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cityvacationpackage',
            name='metaDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityvacationpackage',
            name='metaTitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='directflight',
            name='metaDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directflight',
            name='metaTitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='flightfrom',
            name='metaDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightfrom',
            name='metaTitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalflight',
            name='metaDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalflight',
            name='metaTitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lastminuteflight',
            name='metaDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lastminuteflight',
            name='metaTitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nonstopflight',
            name='metaDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonstopflight',
            name='metaTitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='onewayflight',
            name='metaDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onewayflight',
            name='metaTitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='roundtripflight',
            name='metaDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roundtripflight',
            name='metaTitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
